SELECT Nombre FROM ARTICULOS;

Select Nombre, Precio FROM ARTICULOS;

SELECT Nombre FROM ARTICULOS WHERE Precio > 200;

SELECT * FROM ARTICULOS WHERE Precio BETWEEN 60 and 120;

SELECT Nombre, Precio * 980 FROM ARTICULOS;

SELECT AVG(Precio) FROM ARTICULOS;

SELECT AVG(Precio) FROM ARTICULOS WHERE Fabricante = 2;

SELECT COUNT(*) FROM ARTICULOS WHERE Precio >= 180;

SELECT Nombre, Precio FROM ARTICULOS
WHERE Precio >= 180 ORDER BY Precio DESC, Nombre ASC;

SELECT * 
FROM ARTICULOS INNER JOIN FABRICANTES ON ARTICULOS.Fabricante = FABRICANTES.Codigo;

SELECT ARTICULOS.Nombre, Precio, FABRICANTES.Nombre
FROM ARTICULOS INNER JOIN FABRICANTES ON ARTICULOS.Fabricante = FABRICANTES.Codigo;

SELECT AVG(Precio), Fabricante FROM ARTICULOS
GROUP BY Fabricante;

SELECT AVG(Price), FABRICANTES.Nombre
FROM ARTICULOS INNER JOIN FABRICANTES ON ARTICULOS.Fabricante = FABRICANTES.Codigo
GROUP BY FABRICANTES.Nombre HAVING AVG(Precio) >= 150;

SELECT ARTICULOS.Nombre, ARTICULOS.Precio , FABRICANTES:Nombre
FROM ARTICULOS INNER JOIN FABRICANTES 
ON ARTICULOS.Fabricante = FABRICANTES.Codigo
AND ARTICULOS.Precio = (
    SELECT MAX(Precio) FROM ARTICULOS
    WHERE ARTICULOS.FABRICANTE = FABRICANTE.Codigo
);

INSERT INTO ARTICULOS(Nombre, Precio, Fabricante)
VALUES ('Altavoces', 70, 1);

UPDATE INTO ARTICULOS(Nombre, Precio, Fabricante)
SET Nombre = 'Impresora Laser' WHERE Codigo = 8;

